movieproject/apps/movies/urls.py
from django.urls import path
from movies.views import *
app_name = 'movies'

urlpatterns = [
    path('create/', MovieCreateView.as_view(), name='create_movie'),
    path('list/', MovieListView.as_view(), name='movie_list'),
    path('delete/<int:pk>', MovieDeleteView.as_view(), name='movie_delete'),
    path('update/<int:pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('detail/<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('admin/', admin.site.urls),
    path('movie/',include('movies.urls',namespace='movie')),
]

movieproject/apps/movies/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Movie(models.Model):
    movie = models.CharField(max_length=250)
    description = models.TextField(_("Descrption"), blank = True, null = True)
    year = models.IntegerField(verbose_name =_('Release Year'))
    rating = models.FloatField(_("Movie Rating"), blank = True, null = True)
    cast = models.TextField(_("Cast"), blank = True, null = True)

    class Meta:
       managed = True
       ordering = ['-id']

movieproject/apps/movies/forms.py
from .models import Movie
from django import forms

class CreateMovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['movie','description','year','rating','cast']

movieproject/apps/movies/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from movies import forms
from django.contrib import messages
from .models import Movie
from django.urls import reverse_lazy

class MovieCreateView(CreateView):

    model = Movie
    form_class = forms.CreateMovieForm
    template_name = 'movie/movie_form.html'
    success_url = '/movie/list/'

    def form_valid(self, form, **kwargs):
        movie = form.save(commit=False)
        movie.save()
        messages.success(self.request, 'Movie added successfully!')
        return redirect(self.success_url) 


class MovieListView(ListView):
    model = Movie
    template_name = 'movie/movie_list.html'

class MovieDeleteView(DeleteView):
    model = Movie
    success_url = reverse_lazy('movie:movie_list')

class MovieUpdateView(UpdateView):
    model = Movie
    form_class = forms.CreateMovieForm
    template_name = 'movie/movie_update_form.html'
    success_url = '/movie/list/'

class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movie/movie_detail.html'

movieproject/templates/movie/movie_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

movieproject/templates/movie/movie_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Movie Detail</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: 'Roboto', sans-serif;
    }
    .table-wrapper {
        background: #fff;
        padding: 20px;
        margin: 30px 0;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        font-size: 15px;
        padding-bottom: 10px;
        margin: 0 0 10px;
        min-height: 45px;
    }
    .table-title h2 {
        margin: 5px 0 0;
        font-size: 24px;
    }
    .table-title select {
        border-color: #ddd;
        border-width: 0 0 1px 0;
        padding: 3px 10px 3px 5px;
        margin: 0 5px;
    }
    .table-title .show-entries {
        margin-top: 7px;
    }
    .search-box {
        position: relative;
        float: right;
    }
    .search-box .input-group {
        min-width: 200px;
        position: absolute;
        right: 0;
    }
    .search-box .input-group-addon, .search-box input {
        border-color: #ddd;
        border-radius: 0;
    }
    .search-box .input-group-addon {
        border: none;
        border: none;
        background: transparent;
        position: absolute;
        z-index: 9;
    }
    .search-box input {
        height: 34px;
        padding-left: 28px;     
        box-shadow: none !important;
        border-width: 0 0 1px 0;
    }
    .search-box input:focus {
        border-color: #3FBAE4;
    }
    .search-box i {
        color: #a0a5b1;
        font-size: 19px;
        position: relative;
        top: 2px;
        left: -10px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table td:last-child {
        width: 130px;
    }
    table.table td a {
        color: #a0a5b1;
        display: inline-block;
        margin: 0 5px;
    }
    table.table td a.view {
        color: #03A9F4;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }    
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        padding: 0 10px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 30px !important;
        text-align: center;
    }
    .pagination li a:hover {
        color: #666;
    }   
    .pagination li.active a {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
    .pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }
</style>
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
    // Animate select box length
    var searchInput = $(".search-box input");
    var inputGroup = $(".search-box .input-group");
    var boxWidth = inputGroup.width();
    searchInput.focus(function(){
        inputGroup.animate({
            width: "300"
        });
    }).blur(function(){
        inputGroup.animate({
            width: boxWidth
        });
    });
});
</script>
</head>
<body>
    <div class="container">
        <div class="table-wrapper">         
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h1 class="text-center"><b>Movie Detail</b></h1>
                    </div>
                    
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Movie</th>
                        <th>Description</th>
                        <th>Cast </th>
                        <th>Year</th>
                        <th>Rating</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ object.movie }}</td>
                        <td>{{ object.description }}</td>
                        <td>{{ object.cast }}</td>
                        <td>{{ object.year }}</td>
                        <td>{{ object.rating }}</td>
                    </tr>
                 </tbody>
            </table> 
            <div class="add_btn add_new">
                <a href="{% url 'movies:movie_list' %}" >Back</a>
            </div>  
        </div>
    </div>     
</body>
</html>                                                                 

movieproject/templates/movie/movie_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Create Movie</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
    body{
        color: #fff;
        background: #63738a;
        font-family: 'Roboto', sans-serif;
    }
    .form-control{
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }
    .form-control:focus{
        border-color: #5cb85c;
    }
    .form-control, .btn{        
        border-radius: 3px;
    }
    .create-form{
        width: 400px;
        margin: 0 auto;
        padding: 30px 0;
    }
    .create-form h2{
        color: #636363;
        margin: 0 0 15px;
        text-align: center;
    }
    .create-form h2:before, .create-form h2:after{
        content: "";
        height: 2px;
        width: 30%;
        background: #d4d4d4;
        position: absolute;
        top: 50%;
        z-index: 2;
    }   
    .create-form h2:before{
        left: 0;
    }
    .create-form h2:after{
        right: 0;
    }
    .create-form .hint-text{
        color: #999;
        margin-bottom: 30px;
        text-align: center;
    }
    .create-form form{
        color: #999;
        border-radius: 3px;
        margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .create-form .form-group{
        margin-bottom: 20px;
    }
    .create-form input[type="checkbox"]{
        margin-top: 3px;
    }
    .create-form .btn{        
        font-size: 16px;
        font-weight: bold;      
        min-width: 140px;
        outline: none !important;
    }
    .create-form .row div:first-child{
        padding-right: 10px;
    }
    .create-form .row div:last-child{
        padding-left: 10px;
    }       
    .create-form a{
        color: #fff;
        text-decoration: underline;
    }
    .create-form a:hover{
        text-decoration: none;
    }
    .create-form form a{
        color: #5cb85c;
        text-decoration: none;
    }   
    .create-form form a:hover{
        text-decoration: underline;
    }  
</style>
</head>
<body>
    <div class="create-form">
        <form method="post" role="form" id="movie-create-form" class="movie-create-form" enctype="multipart/form-data">{% csrf_token %}
            <h2>Create Movie</h2>
            <div class="form-group">
                <label for="movie">Movie</label>
                    {{ form.movie }}
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                    {{ form.description }}
            </div>
            <div class="form-group">
                <label for="rating">Rating</label>
                    {{ form.rating }}
            </div>
            <div class="form-group">
                <label for="year">Year</label>
                    {{ form.year }}
            </div>
            <div class="form-group">
                <label for="cast">Cast</label>
                    {{ form.cast }}
            </div>
            <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit submit" value="Submit"/>
            </div>
        </form>
    </div>
</body>
</html>                            

movieproject/templates/movie/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Movie List</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: 'Roboto', sans-serif;
    }
    .table-wrapper {
        background: #fff;
        padding: 20px;
        margin: 30px 0;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        font-size: 15px;
        padding-bottom: 10px;
        margin: 0 0 10px;
        min-height: 45px;
    }
    .table-title h2 {
        margin: 5px 0 0;
        font-size: 24px;
    }
    .table-title select {
        border-color: #ddd;
        border-width: 0 0 1px 0;
        padding: 3px 10px 3px 5px;
        margin: 0 5px;
    }
    .table-title .show-entries {
        margin-top: 7px;
    }
    .search-box {
        position: relative;
        float: right;
    }
    .search-box .input-group {
        min-width: 200px;
        position: absolute;
        right: 0;
    }
    .search-box .input-group-addon, .search-box input {
        border-color: #ddd;
        border-radius: 0;
    }
    .search-box .input-group-addon {
        border: none;
        border: none;
        background: transparent;
        position: absolute;
        z-index: 9;
    }
    .search-box input {
        height: 34px;
        padding-left: 28px;     
        box-shadow: none !important;
        border-width: 0 0 1px 0;
    }
    .search-box input:focus {
        border-color: #3FBAE4;
    }
    .search-box i {
        color: #a0a5b1;
        font-size: 19px;
        position: relative;
        top: 2px;
        left: -10px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table td:last-child {
        width: 130px;
    }
    table.table td a {
        color: #a0a5b1;
        display: inline-block;
        margin: 0 5px;
    }
    table.table td a.view {
        color: #03A9F4;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }    
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        padding: 0 10px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 30px !important;
        text-align: center;
    }
    .pagination li a:hover {
        color: #666;
    }   
    .pagination li.active a {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
    .pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }
    .delete {
        
        margin-left: 60px;
        position: relative;
        top:-25px;
        color:red;
    }
</style>
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
    // Animate select box length
    var searchInput = $(".search-box input");
    var inputGroup = $(".search-box .input-group");
    var boxWidth = inputGroup.width();
    searchInput.focus(function(){
        inputGroup.animate({
            width: "300"
        });
    }).blur(function(){
        inputGroup.animate({
            width: boxWidth
        });
    });
});

$(document).on("click", ".delete",function(e){
    alert("Are you sure you want to delete");
});   
</script>
</head>
<body>
    <div class="container">
        <div class="table-wrapper">         
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h1 class="text-center"><b>Movie List</b></h1>
                    </div>
                    
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Movie</th>
                        <th>Year</th>
                        <th>Rating</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.movie }}</td>
                        <td>{{ object.year }}</td>
                        <td>{{ object.rating }}</td>
                        <td>
                            <a href="{% url 'movies:movie_detail' object.id %}" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
                            <a href="{% url 'movies:movie_update' object.id %}" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <form method="post" action="{% url 'movies:movie_delete' object.id %}">{% csrf_token %}
                                <input type="submit" value="Delete" class="delete" data-toggle="tooltip">
                                
                            </form> 
                        </td>
                    </tr>
                    {% endfor %}
                 </tbody>
                
            </table> 
            <div class="add_btn add_new">
                <a href="{% url 'movies:create_movie' %}" class="add_popup" >Add New</a>
            </div>  
        </div>
    </div>  
</body>
</html>                                                                 

movieproject/templates/movie/movie_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Movie Update</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
    body{
        color: #fff;
        background: #63738a;
        font-family: 'Roboto', sans-serif;
    }
    .form-control{
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }
    .form-control:focus{
        border-color: #5cb85c;
    }
    .form-control, .btn{        
        border-radius: 3px;
    }
    .update-form{
        width: 400px;
        margin: 0 auto;
        padding: 30px 0;
    }
    .update-form h2{
        color: #636363;
        margin: 0 0 15px;
        text-align: center;
    }
    .update-form h2:before, .update-form h2:after{
        content: "";
        height: 2px;
        width: 30%;
        background: #d4d4d4;
        position: absolute;
        top: 50%;
        z-index: 2;
    }   
    .update-form h2:before{
        left: 0;
    }
    .update-form h2:after{
        right: 0;
    }
    .update-form .hint-text{
        color: #999;
        margin-bottom: 30px;
        text-align: center;
    }
    .update-form form{
        color: #999;
        border-radius: 3px;
        margin-bottom: 15px;
        background: #f2f3f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .update-form .form-group{
        margin-bottom: 20px;
    }
    .update-form input[type="checkbox"]{
        margin-top: 3px;
    }
    .update-form .btn{        
        font-size: 16px;
        font-weight: bold;      
        min-width: 140px;
        outline: none !important;
    }
    .update-form .row div:first-child{
        padding-right: 10px;
    }
    .update-form .row div:last-child{
        padding-left: 10px;
    }       
    .update-form a{
        color: #fff;
        text-decoration: underline;
    }
    .update-form a:hover{
        text-decoration: none;
    }
    .update-form form a{
        color: #5cb85c;
        text-decoration: none;
    }   
    .update-form form a:hover{
        text-decoration: underline;
    }  
</style>
</head>
<body>
    <div class="update-form">

    <form method="post">{% csrf_token %}
        <h2>Update Movie Details</h2>
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
    </div>
</body>
</html>                            